name: HTML Update

on:
  workflow_dispatch:

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any dependencies your script requires here
        # pip install requests

    - name: Run update script
      run: python updateHomeCrap.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update HTML content"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
